@baseUrl = http://localhost:8080

### Register one default user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login":"james",
  "password":"password"
}

### Login with default user credentials
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "login":"james",
  "password":"password"
}

### Register john
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login":"john",
  "password":"123"
}

### Login with John credentials
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "login":"john",
  "password":"123"
}
